version: 2.1
orbs:
  ccache: dynomite567/ccache@1.0.1
commands:
  set_environment_vars:
    steps:
    - run:
        command: |
          echo "export ARCH=arm64" >> $BASH_ENV
jobs:
  build:
    environment:
      CREATE_TARBALL: LonganPi-3H-SDK/build/rootfs.tar
    machine:
      image: ubuntu-2204:2024.11.1
    resource_class: medium
    
    steps:
    - checkout:
        path: LonganPi-3H-SDK
    - set_environment_vars
    
    - run:
        name: Install Software
        command: |
          sudo apt update && \
          sudo NEEDRESTART_MODE=a apt install -y sudo qemu-user-static \
          gcc-aarch64-linux-gnu mmdebstrap git binfmt-support make \
          build-essential bison flex make gcc libncurses-dev \
          debian-archive-keyring swig libssl-dev bc python3-setuptools \
          python3-dev libconfuse-dev debhelper fuse2fs rsync kmod cpio \
          debian-keyring fuse ccache zip ca-certificates pkg-config exfatprogs
    
    - run:
        name: Set date
        command: |
          echo "export DATE=`date +%Y%m%d`" >> $BASH_ENV
    
    - run:
        name: Clone genimage
        command: |
          git clone -b v17 https://github.com/pengutronix/genimage.git

    - ccache/restore:
        path: /home/circleci/project/LonganPi-3H-SDK

    - run:
        name: Build genimage
        command: |
          pushd genimage
              ./autogen.sh
              ./configure
              make -j$(nproc)
              sudo make install
          popd

    - run:
        name: Build Linux kernel
        command: |
          pushd LonganPi-3H-SDK
              python3 -m pip install -U pip setuptools 
              git config --global user.email "nop@nop.nop"
              git config --global user.name "nop"
              export PATH="/usr/lib/ccache:/usr/local/opt/ccache/libexec:$PATH"
              sh mkatf.sh
              sh mkuboot.sh
              sh mklinux.sh
          popd

    - ccache/save:
        path: /home/circleci/project/LonganPi-3H-SDK

    - run:
        name: Build CLI image
        command: |
          pushd LonganPi-3H-SDK
              sh mkoverlay.sh
              sudo sh mkrootfs.sh nogui
              sudo sh mkimage.sh
          popd
    
    - run:
        name: Make Checksum file & Compress files
        command: |
          pushd LonganPi-3H-SDK
              sudo xz -z -v -9 -T $(nproc) build/images/sdcard.img
              sudo mv build/images/* ../
          popd
          sudo sha512sum sdcard.img.xz > sdcard.img.xz.sha512
          sudo zip "lm3h-cli-${DATE}.zip" *.xz *.sha512
          sudo rm *.xz *.sha512
    
    - run:
        name: Build XFCE image
        command: |
          pushd LonganPi-3H-SDK
              sudo sh mkrootfs.sh
              sudo sh mkimage.sh
          popd
    
    - run:
        name: Make Checksum file & Compress files & Clean
        command: |
          pushd LonganPi-3H-SDK
              sudo xz -z -v -9 -T $(nproc) build/images/sdcard.img
              sudo mv build/images/* ../
          popd
          sudo sha512sum sdcard.img.xz > sdcard.img.xz.sha512
          sudo zip "lm3h-xfce-${DATE}.zip" *.xz *.sha512
          sudo rm *.xz *.sha512
          sudo rm -rf LonganPi-3H-SDK
          mkdir artifacts && mv lm3h-*.zip artifacts/
    
    - run:
          name: "Publish Release on GitHub"
          command: |
            go install github.com/tcnksm/ghr@latest
            ghr -t ${GITHUB_TOKEN} -u ${CIRCLE_PROJECT_USERNAME} -r ${CIRCLE_PROJECT_REPONAME} \
            -c ${CIRCLE_SHA1} -latest auto -delete "v${DATE}" ./artifacts/
 
workflows:
  mkimg-lpi3h-ci:
    jobs:
    - build
